name: Update DVC

on:
  push:
    branches:
      - main
      - maca
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      message:
        description: "Commit message for DVC update"
        required: true
        default: "Automated DVC and Git update"

jobs:
  update-dvc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python and install DVC
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install DVC
        run: |
          pip install --upgrade pip
          pip install dvc[gs]  # Or adjust based on your remote type

      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 4: Track DVC changes
      - name: Track changes with DVC
        run: |
          dvc add data models  # Adjust paths to your DVC-tracked folders

      # Step 5: Push DVC data to remote
      - name: Push DVC data to remote
        run: dvc push

      # Step 6: Commit DVC changes to Git
      - name: Commit and push changes to Git
        run: |
          git add *.dvc dvc.lock
          git commit -m "${{ github.event.inputs.message }}"
          git push
