name: Test on Data Changes

on:
  push:
    branches:
      - main
      - maca
    paths:
      - "data/**"
      - "*.dvc"
      - ".dvc/**"
      - ".dvcignore"
  pull_request:
    paths:
      - "data/**"
      - "*.dvc"
      - ".dvc/**"
      - ".dvcignore"

jobs:
  data-tests:
    name: Test Data Changes
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install tomli
          pip install coverage
          pip install pytest
          pip install -e .
          pip install dvc[gdrive]

      # Step 4: Initialize DVC (only if not already initialized)
      - name: Initialize DVC
        run: |
          if [ ! -d .dvc ]; then
            echo "Initializing DVC repository..."
            dvc init
          else
            echo "DVC repository already initialized."
          fi

      # Step 5: Configure DVC and Google Drive
      - name: Configure DVC and Google Drive
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive-credentials.json
          dvc remote add -d myremote gdrive://1dzU57nTbziYz9A5phOpLDVYRnUBIqvWZ || echo "Remote already exists"
          dvc remote modify -- local myremote gdrive_use_service_account true
          dvc remote modify myremote --local gdrive_service_account_json_file_path gdrive-credentials.json

      # Step 6: Pull Data with DVC
      - name: Pull Data with DVC
        run: |
          dvc pull || echo "Some data files may be missing; check logs"

      # Step 7: Run data-related tests
      - name: Run data tests
        run: |
          echo "Running data-related tests..."
          pytest tests/data_test.py
