name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # CUDA support is only available for Ubuntu
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install PyTorch with CUDA for Ubuntu
          if [ $RUNNER_OS == "Linux" ]; then
            pip install torch==2.2.0 torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cu118
          else
            # Install CPU-only PyTorch for macOS and Windows
            pip install torch==2.2.0 torchvision==0.17.0
          fi
          # Install other dependencies
          pip install -r requirements.txt
          pip install . -e
          pip list

      - name: Verify PyTorch installation
        run: |
          python -c "import torch; print('CUDA available:', torch.cuda.is_available()); print('Device count:', torch.cuda.device_count())"

      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage
