name: Test on Data Changes

on:
  push:
    paths:
      - "data/**"
      - "*.dvc"
      - ".dvc/**"
      - ".dvcignore"
  pull_request:
    paths:
      - "data/**"
      - "*.dvc"
      - ".dvc/**"
      - ".dvcignore"

jobs:
  data-tests:
    name: Test Data Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install tomli
          pip install coverage
          pip install pytest
          pip install -e .
          pip install dvc[gs]

      - name: Pull Data with DVC
        run: |
          dvc pull

      - name: Run data tests
        run: |
          echo "Running data-related tests..."
          pytest tests/data_test.py
